# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ps-smurf"
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin 'Gus' Knowlden", "Nicolas Viennot", "Ryan Grove", "Paul Schreiber"]
  s.date = "2012-04-12"
  s.description = "Rails plugin to automatically minify JS and CSS when their bundles get cached."
  s.email = "paulschreiber@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/closure-compiler/COPYING",
    "lib/closure-compiler/README",
    "lib/closure-compiler/compiler.jar",
    "lib/closure-compiler/version",
    "lib/jsmin.rb",
    "lib/smurf.rb",
    "lib/smurf/javascript.rb",
    "lib/smurf/noop.rb",
    "lib/smurf/rainpress.rb",
    "lib/smurf/stylesheet.rb",
    "test/integration_test.rb",
    "test/javascript_test.rb",
    "test/rails/app/controllers/application.rb",
    "test/rails/config/application.rb",
    "test/rails/config/boot.rb",
    "test/rails/config/environment.rb",
    "test/rails/config/environments/test.rb",
    "test/rails/config/routes.rb",
    "test/rails/public/javascripts/cache/expected.js",
    "test/rails/public/javascripts/projwcss/jscss.css",
    "test/rails/public/javascripts/testing.js",
    "test/rails/public/stylesheets/bar.css",
    "test/rails/public/stylesheets/cache/expected-basic.css",
    "test/rails/public/stylesheets/foo.css",
    "test/stylesheet_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/paulschreiber/ps-smurf"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Rails plugin to automatically minify JS and CSS when their bundles get cached"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<riot>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<riot>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<riot>, [">= 0"])
  end
end

